### ISSUE TITLE
Curly Brackets Are Not Allowed and Other

### ISSUE THREAD

**Issue by apolokaklab** [TheRealSyler/vscode-sass-indented#16]
the previous version had no problems. But after the latest update this problem arose.
![BUG](https://user-images.githubusercontent.com/30395693/64148850-99865780-ce4e-11e9-9d86-3cff3318ed73.png)
![BUG2](https://user-images.githubusercontent.com/30395693/64149507-43b2af00-ce50-11e9-8da9-b3f9e1e0772e.png)

**Comment by TheRealSyler** [comment]
@apolokaklab i added a linter and just added the rule that curly brackets are not allowed, i didn't know that there is a legitimate use case for curly brackets, and i also added a simple rule that checks if variables are declared twice, the reason why i didn't test it thoroughly, is that i wanted to fix some bugs so some unfinished features just got added prematurely, the fix for know is go to the settings and set `sass.lint.enable` to `false`, also if you have formatting enabled it might screw up your code so you also might want to disable that.

**Comment by apolokaklab** [comment]
Thanks for the answer, for this problem solver I am back again to version 1.6.0.

**Comment by TheRealSyler** [comment]
@apolokaklab  try the next version when it comes out, if i didn't fix the problems that you are having please open another issue or add comment on this one.

**Comment by TheRealSyler** [comment]
@apolokaklab  by next version i mean 1.6.4, 1.6.3 fixed some formatter issues.

**Comment by apolokaklab** [comment]
Oke, thanks, I don't think why vscode doesn't support sass, just scss :D

**Comment by TheRealSyler** [comment]
The linter is now disabled by default, im closing this for now because im not going to work on the linter anytime soon.
