### ISSUE TITLE
Empty Property error on any property line

### ISSUE THREAD

**Issue by mv-go** [TheRealSyler/vscode-sass-indented#87]
**Describe the bug**
I'm getting `Empty Property` error on pretty much any line that I write.

**To Reproduce**
1. Install plugin
2. Create a test.sass file anywhere on your system.
3. Try applying font-size and red color to a div
4. Error will show up on both lines

**Expected behavior**
No error for valid property definitions.

**Screenshots**
<img width="442" alt="image" src="https://user-images.githubusercontent.com/28507807/124791370-aac1b300-df54-11eb-9c5e-77790544dec3.png">
```sass
div
    font-size: 14px
    color: red
```

**Additional context**
Same error shows up for any simplest line of code that I can come up with: font-size, width, color, etc.

I only have this plugin that would mess around with SASS installed for my IDE. If I disable this plugin, all content inside my .sass file becomes gray, which suggests that no other plugin is trying to parse something there.

**Comment by mv-go** [comment]
I tried googling it up and looked through issues in this repo - couldn't find anything related. Probably something stupid on my side, but I can't figure it out

**Comment by TheRealSyler** [comment]
@mv-go go to settings `sass.lint` and make sure that the checkbox is disabled, its a deprecated feature that is still in the extension because im too lazy to remove it, but i probably should since every now and then people get confused by weird errors.
![Untitled](https://user-images.githubusercontent.com/46901787/124796758-d0998880-df51-11eb-9059-8acb510ed847.png)
